#!/bin/bash

xsetroot -cursor_name left_ptr
nitrogen --restore
setxkbmap gb
xmodmap .Xmodmap

xset s off
xset -dpms
# keyboard rate: default is 660ms / 25 Hz
xset r rate 300 30

#conky & 2&1>/dev/null
#/usr/bin/xflux -l 49.45203 -g 11.07675 
