#!/bin/sh

DESKS="$(seq 1 9) 0"
i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
    let i++
done
NMON=$i

bspc config split_ratio 0.50
bspc config border_width 2
bspc config window_gap 8
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config auto_cancel true

bspc config focused_border_color "#508F50"
bspc config normal_border_color "#3F3E3B"
bspc config presel_border_color "#FF003F"
bspc config active_frame_opacity 0
bspc config normal_frame_opacity 0
bspc config focused_frame_opacity 0.2
bspc config pointer_modifier mod4

polybar example &
