#!/bin/bash

xsetroot -cursor_name left_ptr
nitrogen --restore
setxkbmap gb
xmodmap .Xmodmap

xset s off
xset -dpms
# keyboard rate: default is 660ms / 25 Hz
xset r rate 300 30

compton -b
xcape &
sxhkd &
tint2 &
