#!/bin/sh

[ -z $XDG_RUNTIME_DIR ] && export XDG_RUNTIME_DIR="/run/user/$(id -u)"
export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/dbus/user_bus_socket"
# Start GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --components=pkcs11,secrets,ssh,gpg --start)
export GNOME_KEYRING_CONTROL GPG_AGENT_INFO SSH_AUTH_SOCK

export PATH="$HOME/.local/bin:$PATH"
export PAGER=less
export EDITOR=vim
export BROWSER=firefox
# Smart case searching as in Vim
export LESS="-Ri"

# XDG basedir specification
[ -z $XDG_CONFIG_HOME ] && export XDG_CONFIG_HOME="$HOME/.config"
[ -z $XDG_DATA_HOME ] && export XDG_DATA_HOME="$HOME/.local/share"
[ -z $XDG_CACHE_HOME ] && export XDG_CACHE_HOME="$HOME/.cache"
if [ -z $XDG_DATA_DIRS ]; then
    export XDG_DATA_DIRS="/usr/local/share:/usr/share"
else
    export XDG_DATA_DIRS="/usr/local/share:/usr/share:$XDG_DATA_DIRS"
fi
if [ -z $XDG_CONFIG_DIRS ]; then
    export XDG_CONFIG_DIRS="/etc/xdg"
else
    export XDG_CONFIG_DIRS="/etc/xdg:$XDG_CONFIG_DIRS"
fi

# Environment variables for programs
export HGRCPATH="$XDG_CONFIG_HOME/mercurial/hgrc"
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
export GVIMINIT='let $MYGVIMRC="$XDG_CONFIG_HOME/vim/gvimrc" | source $MYGVIMRC'
export VIMPERATOR_INIT=":source $XDG_CONFIG_HOME/vimperator/vimperatorrc"
export TASKRC="$XDG_CONFIG_HOME/task/taskrc"
export TEXMFHOME="$XDG_DATA_HOME/texmf"
